dist: trusty
services:
  - xvfb
  
  
#Ensuring java.awt.headless = false
#https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-xvfb-to-run-tests-that-require-a-gui
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"


language: java

jdk:
  - oraclejdk8
  
branches:
  only:
    - main
